### PR TITLE
Fixed multi thread logic, added logic to speed up the hang up process, a...

### PR DESCRIPTION
**Pull request by MichaelGCox**
...dd the ILibrary interface and the logic to use it.

### CODE REVIEW

**Comment by tmakaro** [comment]
Hi Michael, could you remove the ILibrary from core and the changes to the core LineManager and instead modify your plugin constructor, the one that implements IVoice, to do that work?

Since you hard coded the library name, I assume you just forgot to clean this up. Anyways, it's not needed in core.

**Comment by MichaelGCox** [comment]
The problem I have is that I can only invoke the Start Library once.  I cannot invoke it for every line.  Using the LineManger was the only simple way I found to do that.  Also I did not want to modify the other plugins with the required methods so I did not want to extend the IVoice interface with those methods.

If you have another idea for a solution I am happy to refactor.

Thanks,


Michael Cox | atrieveERP Architect
[srb-image]
1632 Dickson Ave.  Suite 400 Kelowna, BC V1Y 7T2
T: 866 998 2801 ext. 2154
Michael.Cox@srb-es.com<mailto:Michael.Cox@srb-es.com>

Follow SRB:  [cid:image008.png@01CF9B81.6DA9BA40] <http://www.linkedin.com/company/srb-education-solutions-inc>   [cid:image009.png@01CF9B81.6DA9BA40] <http://www.twitter.com/SRBEd>

Sign Up for Email Updates<http://visitor.r20.constantcontact.com/d.jsp?llr=ak5cyfeab&p=oi&m=1103999629632&sit=enodtrsfb&f=06a103f7-d53f-4bc2-a9d7-3cb000188b52> | Opt-out Options<http://www.srb-es.com/EmailOptions.aspx> | Privacy Policy<http://www.srbeducationsolutions.com/privacy.aspx>

**Comment by tmakaro** [comment]
yup. I see you have a static isStarted in LineManager. Moving that into your class that implements IVoice would work the same way. I suggest you use lock on that as well to make it threadsafe.

**Comment by ivrtoolkitsupport** [comment]
These have already been merged

**Pull request closed without merging**
